spring:
  application:
    name: ai-code-helper
  profiles:
    active: local
langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-plus
        api-key: Your API Key
      embedding-model:
          model-name: text-embedding-v4
          api-key: Your API Key